import React,{useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {EverydaySituation} from '../types';
import {EVERYDAY_SITUATIONS,TEACHER_GUIDE} from '../data/curriculumData';
type P={isOpen:boolean;onClose:()=>void;reproductionUnlocked:boolean;onToggleReproduction:(v:boolean)=>void;studentQueries:any[];onClearQueries:()=>void;onLaunchProjector:(s:EverydaySituation)=>void;onResetInvestigation:()=>void};
export const TeacherDashboard:React.FC<P>=({isOpen,onClose,onLaunchProjector})=>{
 const [ok,setOk]=useState(false),[session,setSession]=useState<any>(null),[issuedCode,setIssuedCode]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[items,setItems]=useState<any[]>([]),[questions,setQuestions]=useState<any[]>([]),[search,setSearch]=useState(''),[course,setCourse]=useState('all'),[activity,setActivity]=useState('all'),[selected,setSelected]=useState(''),[tab,setTab]=useState('trabajos');
 const load=async()=>{if(!supabase)return;const [r,q]=await Promise.all([supabase.from('student_responses').select('id,student_id,activity,response,created_at,reviewed,students(first_name,last_name,course)').order('created_at',{ascending:false}),supabase.from('anonymous_questions').select('*').order('created_at',{ascending:false})]);if(r.error||q.error){setError('No se pudieron cargar los datos. Revisá la configuración y los permisos.');return}setItems(r.data||[]);setQuestions(q.data||[])};useEffect(()=>{if(ok)void load()},[ok]);if(!isOpen)return null;
 const login=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase){setError('Supabase no está configurado.');return}const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error||!data.session){setError('No se pudo iniciar sesión.');return}if(data.session.user.app_metadata?.role!=='docente'){await supabase.auth.signOut();setError('Esta cuenta no tiene permisos docentes.');return}setPassword('');setSession(data.session);setOk(true)};
 const issueCode=async()=>{if(!session)return;const code=crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase();const r=await fetch('/api/teacher/expediente2-code',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({code})});if(!r.ok){setError('No se pudo crear el código. Verificá que tu cuenta esté autorizada como docente.');return}setIssuedCode(code);setError('')};
 const disableCode=async()=>{if(!session)return;const r=await fetch('/api/teacher/expediente2-code',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({enabled:false})});if(!r.ok)setError('No se pudo desactivar el código.');else setIssuedCode('')};
 const filtered=items.filter(x=>{const s=x.students||{};return(!search||`${s.first_name} ${s.last_name}`.toLowerCase().includes(search.toLowerCase()))&&(course==='all'||s.course===course)&&(activity==='all'||x.activity===activity)&&(!selected||selected===x.student_id)});
 const update=async(id:string,reviewed:boolean)=>{const {error}=await supabase!.from('student_responses').update({reviewed}).eq('id',id);if(error)setError('No se pudo guardar.');else load()};const remove=async(id:string)=>{const {error}=await supabase!.from('student_responses').delete().eq('id',id);if(error)setError('No se pudo eliminar.');else load()};
 return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/70 p-3"><div className="my-6 max-h-[92vh] w-full max-w-5xl overflow-auto rounded-3xl bg-white shadow-2xl"><header className="flex justify-between bg-indigo-800 px-6 py-4 text-white"><div><h2 className="font-bold">Panel docente</h2><p className="text-xs">Trabajos identificados y buzón anónimo</p></div><button onClick={onClose}>Cerrar ✕</button></header>
 {!ok?<form onSubmit={login} className="mx-auto max-w-md space-y-4 p-8"><h3 className="text-lg font-bold">Ingreso docente</h3><p className="text-sm text-slate-600">Cuenta docente autorizada en Supabase.</p><input type="email" required placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border p-3"/><input type="password" required placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border p-3"/>{error&&<p className="text-rose-700">{error}</p>}<button className="w-full rounded-xl bg-indigo-700 p-3 font-bold text-white">Ingresar</button></form>:<main className="p-5"><div className="mb-4 flex flex-wrap gap-2"><button onClick={()=>setTab('trabajos')} className="rounded bg-indigo-50 px-3 py-2">Respuestas ({items.length})</button><button onClick={()=>setTab('buzon')} className="rounded bg-rose-50 px-3 py-2">Buzón anónimo ({questions.length})</button><button onClick={()=>setTab('guia')} className="rounded bg-amber-50 px-3 py-2">Guía docente</button><button onClick={()=>setTab('acceso')} className="rounded bg-emerald-50 px-3 py-2">Expediente 2</button><button className="ml-auto" onClick={async()=>{await supabase?.auth.signOut();setOk(false)}}>Salir</button></div>{error&&<p className="text-rose-700">{error}</p>}
 {tab==='trabajos'&&<><div className="grid gap-2 sm:grid-cols-4"><input placeholder="Buscar alumno" value={search} onChange={e=>setSearch(e.target.value)} className="rounded-xl border p-2"/><select value={course} onChange={e=>setCourse(e.target.value)} className="rounded-xl border p-2"><option value="all">Todos los cursos</option>{[...new Set(items.map(x=>x.students?.course).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select><select value={activity} onChange={e=>setActivity(e.target.value)} className="rounded-xl border p-2"><option value="all">Todas las actividades</option>{[...new Set(items.map(x=>x.activity))].map(x=><option key={x}>{x}</option>)}</select><select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-xl border p-2"><option value="">Todos los alumnos</option>{[...new Map(items.map(x=>[x.student_id,x.students])).entries()].map(([id,s]:any)=><option key={id} value={id}>{s?.last_name}, {s?.first_name} · {s?.course}</option>)}</select></div><div className="mt-4 space-y-3">{filtered.map(x=><article key={x.id} className="rounded-xl border p-4"><div className="flex justify-between"><b>{x.students?.first_name} {x.students?.last_name} · {x.students?.course}<small className="block text-indigo-800">{x.activity}</small></b><time className="text-xs">{new Date(x.created_at).toLocaleString('es-AR')}</time></div><p className="my-3 whitespace-pre-wrap rounded bg-slate-50 p-3">{x.response}</p><div className="text-right"><button onClick={()=>void update(x.id,!x.reviewed)} className="mr-3 text-emerald-700">{x.reviewed?'✓ Revisada':'Marcar revisada'}</button><button onClick={()=>void remove(x.id)} className="text-rose-700">Eliminar</button></div></article>)}{!filtered.length&&<p className="p-8 text-center">No hay envíos todavía.</p>}</div></>}
 {tab==='acceso'&&<section className="space-y-3 rounded-2xl border p-5"><h3 className="font-bold">Acceso al Expediente 2</h3><p className="text-sm text-slate-600">Generá un código cuando quieras abrir esta etapa. Copialo y compartilo con el curso; por seguridad se muestra una sola vez. Al generar otro código, el anterior deja de funcionar para nuevos accesos.</p><div className="flex flex-wrap gap-2"><button onClick={()=>void issueCode()} className="rounded-xl bg-indigo-700 px-4 py-2 font-bold text-white">Generar código</button><button onClick={()=>void disableCode()} className="rounded-xl border px-4 py-2">Desactivar código</button></div>{issuedCode&&<div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs">Código para compartir:</p><strong className="select-all text-2xl tracking-widest">{issuedCode}</strong><p className="text-xs">Anotalo ahora; no se podrá volver a consultar desde el panel.</p></div>}</section>}
 {tab==='buzon'&&questions.map(q=><article key={q.id} className="my-3 rounded-xl border p-4"><small>Anónima · {q.category} · {new Date(q.created_at).toLocaleString('es-AR')}</small><p className="font-bold">{q.question}</p><p>{q.answer}</p></article>)}
 {tab==='guia'&&<><h3 className="font-bold">{TEACHER_GUIDE.title}</h3><p>{TEACHER_GUIDE.purpose}</p>{TEACHER_GUIDE.didacticMoments.map(m=><p key={m.stage}><b>{m.stage}</b>: {m.suggestedActivity}</p>)}{EVERYDAY_SITUATIONS.map(s=><button key={s.id} className="m-1 rounded border p-2" onClick={()=>{onClose();onLaunchProjector(s)}}>{s.title}</button>)}</>}</main>}</div></div>;
};
